### ISSUE TITLE
Remove Versioning from VirtualBucket API

### ISSUE THREAD

**Issue by nosyliam** [metaprov/modelaapi#11]
https://github.com/metaprov/modelaapi/blob/85e5ccae8ef75d973f7a113363856322120cd8ba/pkg/apis/infra/v1alpha1/virtualbucket_types.go#L82

**Comment by nosyliam** [comment]
Also remove:
https://github.com/metaprov/modelaapi/blob/85e5ccae8ef75d973f7a113363856322120cd8ba/pkg/apis/infra/v1alpha1/virtualbucket_types.go#L103

**Comment by tmeshorer** [comment]
This is AWS versioning support

https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html
