### ISSUE TITLE
Add ClusterIssuer name to the ServingSite API

### ISSUE THREAD

**Issue by nosyliam** [metaprov/modelaapi#17]
The IngressSpec API must have a field `ClusterIssuer` which allows system administrators to specify a cert-manager ClusterIssuer resource that will provide TLS certificats to the Ingress. If the field is specified with a ServingSite resource, the resource controller should append the TLS section (which contains all the hosts listed) to the Ingress and add the cert-manager annotation: 
i.e. `cert-manager.io/cluster-issuer: "modela-ingress-issuer"`

**Comment by tmeshorer** [comment]
Do you have the cluster issuer yaml ?.

I added the field.

**Comment by tmeshorer** [comment]
added the field
