### ISSUE TITLE
Change the GRPCInferenceService API to fetch models by version

### ISSUE THREAD

**Issue by nosyliam** [metaprov/modelaapi#2]
Currently, the GRPCInferenceService has routes to retrieve model information and send inference requests by name but ideally it will fetch the model by version. The supported routes should be:
POST/GET `/model/{version}` -> send predict request to a single model version/fetch information of model w/ the version
POST `/predict` -> automatically route the prediction request to a model determined by the proxy
GET `/predictor` -> get information about the predictor hosting the `GRPCInferenceService`

~~Additionally, we should remove `ModelVersion` from the `ModelDeploymentSpec` API since it should be inferred from the model itself.~~

**Comment by tmeshorer** [comment]
rpc PredictVersion(PredictRequest) returns (PredictResponse) {
    option (google.api.http) = {
      post: "/predictors/{predictor}/models/{version}"
      body: "*"
    };
  }

  rpc Predict(PredictRequest) returns (PredictResponse) {
    option (google.api.http) = {
      post: "/predictors/{predictor}/predict"
      body: "*"
    };
  }

**Comment by tmeshorer** [comment]
Fixed.
