### ISSUE TITLE
Move `TriggeredBy` to the ModelClass status

### ISSUE THREAD

**Issue by nosyliam** [metaprov/modelaapi#48]
```	TriggeredBy catalog.TriggerType `json:"triggeredBy,omitempty" protobuf:"bytes,10,opt,name=triggeredBy"```

**Comment by nosyliam** [comment]
Also fix the protobuf name for this line:
```	FlatFile *data.FlatFileFormatSpec `json:"flatfile,omitempty" protobuf:"bytes,5,opt,name=flatfile"```
Should be `flatFile`

**Comment by tmeshorer** [comment]
This is part of the model class run.
